apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-maintainer
  namespace: elastic-maintainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-maintainer-secrets
  namespace: elastic-maintainer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-maintainer-secrets
  namespace: elastic-maintainer
subjects:
  - kind: ServiceAccount
    name: elastic-maintainer
    namespace: elastic-maintainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elastic-maintainer-secrets
